'use strict';

const WEAPON_TYPES = {
  sns: { id: 'sns', name: 'Sword & Shield', short: 'SnS' },
  gs:  { id: 'gs',  name: 'Great Sword',    short: 'GS'  },
  ls:  { id: 'ls',  name: 'Long Sword',     short: 'LS'  },
  hmr: { id: 'hmr', name: 'Hammer',         short: 'HMR' },
  db:  { id: 'db',  name: 'Dual Blades',    short: 'DB'  },
  lnc: { id: 'lnc', name: 'Lance',          short: 'LNC' },
  gl:  { id: 'gl',  name: 'Gunlance',       short: 'GL'  },
  cb:  { id: 'cb',  name: 'Charge Blade',   short: 'CB'  },
  lbg: { id: 'lbg', name: 'Light Bowgun',   short: 'LBG' },
  bow: { id: 'bow', name: 'Bow',            short: 'Bow' },
  hbg: { id: 'hbg', name: 'Heavy Bowgun',   short: 'HBG' },
};

const WEAPON_TYPE_ORDER = ['sns','gs','ls','hmr','db','lnc','gl','cb','lbg','bow','hbg'];

const ARMOR_SLOTS = ['head','chest','arms','waist','legs'];
const ARMOR_SLOT_NAMES = {
  head:  'Helm',
  chest: 'Mail',
  arms:  'Vambraces',
  waist: 'Coil',
  legs:  'Greaves',
};

const ELEMENT_META = {
  fire:    { name: 'Fire',    color: '#ef5350' },
  water:   { name: 'Water',   color: '#42a5f5' },
  thunder: { name: 'Thunder', color: '#ffca28' },
  ice:     { name: 'Ice',     color: '#80deea' },
  dragon:  { name: 'Dragon',  color: '#ab47bc' },
  poison:  { name: 'Poison',  color: '#ce93d8' },
  none:    { name: '—',  color: '#78909c' },
};

// Weapon types available per starting grade (grade = monster's star rating)
const WEAPONS_BY_TIER = {
  1: ['sns','gs','cb','gl','lbg','hbg'],
  2: ['sns','gs','ls','cb','gl','lbg','hbg'],
  3: ['sns','gs','ls','hmr','cb','gl','lbg','hbg'],
  4: ['sns','gs','ls','hmr','lnc','cb','gl','lbg','bow'],
  5: ['sns','gs','ls','hmr','db','lnc','gl','cb','lbg','bow','hbg'],
  6: ['sns','gs','ls','hmr','db','lnc','gl','cb','lbg','bow','hbg'],
};

const WEAPON_DESCRIPTORS = {
  sns: 'Edge', gs: 'Blade', ls: 'Sword', hmr: 'Hammer', db: 'Fangs',
  lnc: 'Lance', gl: 'Gunlance', cb: 'Strongarm', lbg: 'Blitz', bow: 'Bow', hbg: 'Assault',
};

// Display names for common (generic) materials
const COMMON_MATERIAL_NAMES = {
  'iron_ore':           'Iron Ore',
  'flowfern':           'Flowfern',
  'machalite_ore':      'Machalite Ore',
  'dragonite_ore':      'Dragonite Ore',
  'earth_crystal':      'Earth Crystal',
  'carpenterbug':       'Carpenterbug',
  'monster_bone_s':     'Monster Bone S',
  'fire_herb':          'Fire Herb',
  'monster_bone_m':     'Monster Bone M',
  'monster_bone_l':     'Monster Bone L',
  'monster_bone_plus':  'Monster Bone+',
  'elder_dragon_blood': 'Elder Dragon Blood',
  'dragonfell_berry':   'Dragonfell Berry',
  'godbug':             'Godbug',
  'nitroshroom':        'Nitroshroom',
  'parashroom':         'Parashroom',
  'sleep_herb':         'Sleep Herb',
  'snow_herb':          'Snow Herb',
  'thunderbug':         'Thunderbug',
  'toadstool':          'Toadstool',
  'wyvern_gem_shard':   'Wyvern Gem Shard',
};

// First word of exclusive mat ID → display suffix appended to monster name
const EXCLUSIVE_PART_NAMES = {
  'scale': 'Scale', 'claw': 'Claw', 'tail': 'Tail', 'hide': 'Hide',
  'shell': 'Shell', 'body': 'Pelt',  'plate': 'Plate', 'bone': 'Bone',
  'gem':   'Gem',   'head': 'Head',  'wing': 'Wing',   'blood': 'Blood',
  'bag':   'Sac',   'clamp': 'Clamp',
};

// ─── Monster roster (66 real monsters from mhnow.me, sorted by grade) ─────────
// commons: slot keys → generic material ID (e.g. 'r1_1' → 'iron_ore')
// exclusive: array of monster-specific part IDs; index 0 may be {weapon, armor}
// Grade upgrade steps: 0 = not crafted, 1-N where N = (11 - stars) * 5 = max upgrades to G10
const MONSTERS = [
  { id: "kulu_ya_ku", name: "Kulu-Ya-Ku", prefix: "Kulu",
    stars: 1, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_khaki", "armor": "hide_khaki"}, "head_khaki", "body_orange", "scale_khaki", "hide_khaki"] },
  { id: "barroth", name: "Barroth", prefix: "Barroth",
    stars: 1, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_warm", "armor": "shell_warm"}, "tail_warm", "head_warm", "body_warm", "shell_warm"] },
  { id: "great_jagras", name: "Great Jagras", prefix: "Jagras",
    stars: 1, element: "water", color: "#42a5f5",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "flowfern", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_yellow", "armor": "hide_yellow"}, "claw_yellow", "body_yellow", "scale_yellow", "gem_yellow"] },
  { id: "pukei_pukei", name: "Pukei-Pukei", prefix: "Pukei",
    stars: 1, element: "poison", color: "#ce93d8",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "toadstool", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_grass", "armor": "shell_grass"}, "tail_grass", "bag_grass", "wing_grass", "scale_grass"] },
  { id: "chatacabra", name: "Chatacabra", prefix: "Chatacabra",
    stars: 2, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_green", "armor": "hide_green"}, "shell_green", "head_green", "scale_green", "shell_green"] },
  { id: "arzuros", name: "Arzuros", prefix: "Arzuros",
    stars: 2, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "godbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "hide_blue", "armor": "shell_blue"}, "claw_blue", "body_blue", "hide_blue", "body_blue"] },
  { id: "basarios", name: "Basarios", prefix: "Basarios",
    stars: 2, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "fire_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "shell_grey", "armor": "body_grey"}, "tail_grey", "wing_grey", "body_grey", "wing_grey"] },
  { id: "quematrice", name: "Quematrice", prefix: "Quematrice",
    stars: 2, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "fire_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_blue", "armor": "hide_blue"}, "tail_blue", "head_red", "scale_blue", "blood_red"] },
  { id: "tobi_kadachi", name: "Tobi-Kadachi", prefix: "Tobi",
    stars: 2, element: "thunder", color: "#ffca28",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "thunderbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "claw_green", "armor": "scale_green"}, "hide_green", "wing_green", "scale_green", "body_green"] },
  { id: "tzitzi_ya_ku", name: "Tzitzi-Ya-Ku", prefix: "Tzitzi",
    stars: 2, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "thunderbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_blue", "armor": "hide_blue"}, "claw_blue", "body_blue", "hide_blue", "body_blue"] },
  { id: "lagombi", name: "Lagombi", prefix: "Lagombi",
    stars: 2, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "snow_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "hide_silver", "armor": "head_sliver"}, "claw_silver", "body_silver", "hide_silver", "head_sliver"] },
  { id: "great_wroggi", name: "Great Wroggi", prefix: "Wroggi",
    stars: 2, element: "poison", color: "#ce93d8",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "toadstool", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "bone_warm", "armor": "hide_warm"}, "claw_warm", "head_warm", "bone_warm", "head_warm"] },
  { id: "great_girros", name: "Great Girros", prefix: "Girros",
    stars: 2, element: "thunder", color: "#ffca28",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "parashroom", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "claw_grey", "armor": "scale_grey"}, "tail_grey", "body_grey", "scale_grey", "claw_grey"] },
  { id: "radobaan", name: "Radobaan", prefix: "Radobaan",
    stars: 2, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "sleep_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_silver", "armor": "scale_silver"}, "tail_silver", "shell_silver", "scale_silver", "body_silver"] },
  { id: "paolumu", name: "Paolumu", prefix: "Paolumu",
    stars: 3, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "godbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_silver", "armor": "hide_silver"}, "wing_silver", "shell_pink", "scale_silver", "shell_pink"] },
  { id: "banbaro", name: "Banbaro", prefix: "Banbaro",
    stars: 3, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "shell_khaki", "armor": "body_khaki"}, "tail_khaki", "hide_khaki", "shell_khaki", "claw_khaki"] },
  { id: "aknosom", name: "Aknosom", prefix: "Aknosom",
    stars: 3, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "fire_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_silver", "armor": "body_silver"}, "head_red", "hide_red", "scale_silver", "body_silver"] },
  { id: "jyuratodus", name: "Jyuratodus", prefix: "Jyura",
    stars: 3, element: "water", color: "#42a5f5",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "flowfern", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_khaki", "armor": "shell_khaki"}, "claw_khaki", "body_khaki", "scale_khaki", "shell_khaki"] },
  { id: "volvidon", name: "Volvidon", prefix: "Volvidon",
    stars: 3, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "parashroom", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "shell_red", "armor": "body_red"}, "claw_red", "bone_red", "body_red", "claw_red"] },
  { id: "bishaten", name: "Bishaten", prefix: "Bishaten",
    stars: 3, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "hide_blue", "armor": "body_blue"}, "shell_blue", "claw_blue", "body_blue", "claw_blue"] },
  { id: "garangolm", name: "Garangolm", prefix: "Garang.",
    stars: 4, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "godbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_brown", "armor": "shell_brown"}, "tail_brown", "body_brown", "scale_khaki", "body_brown"] },
  { id: "odogaron", name: "Odogaron", prefix: "Odogaron",
    stars: 4, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_wine", "armor": "body_wine"}, "tail_wine", "claw_wine", "scale_wine", "plate_wine"] },
  { id: "anjanath", name: "Anjanath", prefix: "Anja",
    stars: 4, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "fire_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "claw_pink", "armor": "scale_pink"}, "tail_pink", "bone_pink", "scale_pink", "plate_pink"] },
  { id: "almudron", name: "Almudron", prefix: "Almudron",
    stars: 4, element: "water", color: "#42a5f5",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "flowfern", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_brown", "armor": "shell_brown"}, "tail_brown", "claw_brown", "body_red", "body_red"] },
  { id: "shogun_ceanataur", name: "Shogun Ceanataur", prefix: "Shogun",
    stars: 4, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "flowfern", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_blue", "armor": "clamp_blue"}, "clamp_blue", "head_grey", "scale_blue", "scale_blue"] },
  { id: "khezu", name: "Khezu", prefix: "Khezu",
    stars: 4, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "thunderbug", "r1_3": "monster_bone_s", "r2_1": "machalite_ore", "r2_2": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus", "r3_3": "dragonite_ore", "r3_4": "earth_crystal"},
    exclusive: [{"weapon": "claw_silver", "armor": "hide_silver"}, "blood_silver", "body_silver", "hide_silver", "body_silver"] },
  { id: "barioth", name: "Barioth", prefix: "Barioth",
    stars: 4, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "snow_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "claw_silver", "armor": "shell_silver"}, "tail_silver", "body_silver", "claw_silver", "claw_orange"] },
  { id: "beotodus", name: "Beotodus", prefix: "Beotodus",
    stars: 4, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "snow_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_blue", "armor": "shell_blue"}, "body_blue", "claw_blue", "scale_blue", "body_blue"] },
  { id: "lunagaron", name: "Lunagaron", prefix: "Luna.",
    stars: 4, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "snow_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_blue", "armor": "shell_blue"}, "body_blue", "claw_orange", "scale_blue", "claw_orange"] },
  { id: "gossharag", name: "Gossharag", prefix: "Gossharag",
    stars: 4, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "snow_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "body_silver", "armor": "hide_blue"}, "claw_blue", "claw_blue", "shell_blue", "body_silver"] },
  { id: "rathian", name: "Rathian", prefix: "Rathian",
    stars: 4, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "toadstool", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_forest", "armor": "shell_green"}, "wing_forest", "body_forest", "scale_forest", "plate_green"] },
  { id: "somnacanth", name: "Somnacanth", prefix: "Somna.",
    stars: 4, element: "water", color: "#42a5f5",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "sleep_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_yellow", "armor": "shell_yellow"}, "claw_yellow", "body_purple", "scale_yellow", "body_purple"] },
  { id: "magnamalo", name: "Magnamalo", prefix: "Magn.",
    stars: 4, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "nitroshroom", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_purple", "armor": "shell_purple"}, "tail_purple", "claw_yellow", "body_purple", "plate_purple"] },
  { id: "brute_tigrex", name: "Brute Tigrex", prefix: "B.Tigrex",
    stars: 5, element: "none", color: "#78909c",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "carpenterbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_grey", "armor": "shell_grey"}, "tail_grey", "claw_grey", "claw_grey", "head_grey", "plate_grey"] },
  { id: "nargacuga", name: "Nargacuga", prefix: "Nargacuga",
    stars: 5, element: "none", color: "#78909c",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "godbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_grey", "armor": "hide_grey"}, "tail_grey", "claw_grey", "body_grey", "wing_grey", "body_grey"] },
  { id: "seregios", name: "Seregios", prefix: "Seregios",
    stars: 5, element: "none", color: "#78909c",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_yellow", "armor": "scale_yellow"}, "scale_yellow", "claw_yellow", "claw_yellow", "tail_yellow", "plate_yellow"] },
  { id: "diablos", name: "Diablos", prefix: "Diablos",
    stars: 5, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "sub",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_brown", "armor": "shell_brown"}, "body_brown", "body_brown", "shell_brown", "body_brown"] },
  { id: "black_diablos", name: "Black Diablos", prefix: "B.Diablos",
    stars: 5, element: "none", color: "#78909c",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "monster_bone_s", "r1_2": "godbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_grey", "armor": "shell_grey"}, "body_grey", "body_grey", "shell_grey", "body_grey"] },
  { id: "rajang", name: "Rajang", prefix: "Rajang",
    stars: 5, element: "thunder", color: "#ffca28",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "thunderbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "claw_yellow", "armor": "body_grey"}, "tail_yellow", "claw_grey", "claw_yellow", "claw_yellow", "body_yellow"] },
  { id: "tigrex", name: "Tigrex", prefix: "Tigrex",
    stars: 5, element: "none", color: "#78909c",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "carpenterbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_yellow", "armor": "shell_yellow"}, "tail_yellow", "claw_yellow", "claw_yellow", "head_yellow", "plate_yellow"] },
  { id: "espinas", name: "Espinas", prefix: "Espinas",
    stars: 5, element: "fire", color: "#ef5350",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "fire_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_green", "armor": "shell_green"}, "tail_green", "claw_red", "scale_green", "body_red", "plate_green"] },
  { id: "rathalos", name: "Rathalos", prefix: "Rathalos",
    stars: 5, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "fire_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_red", "armor": "claw_red"}, "tail_red", "body_red", "scale_red", "plate_red"] },
  { id: "azure_rathalos", name: "Azure Rathalos", prefix: "A.Rathalos",
    stars: 5, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "sub",
    commons: {"r1_1": "iron_ore", "r1_2": "fire_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_blue", "armor": "claw_blue"}, "tail_blue", "body_blue", "scale_blue", "plate_blue"] },
  { id: "glavenus", name: "Glavenus", prefix: "Glavenus",
    stars: 5, element: "fire", color: "#ef5350",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "fire_herb", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_red", "armor": "shell_purple"}, "tail_purple", "bone_red", "claw_purple", "shell_purple", "plate_red"] },
  { id: "coral_pukei_pukei", name: "Coral Pukei-Pukei", prefix: "C.Pukei",
    stars: 5, element: "water", color: "#42a5f5",
    isEvent: false, recipeGroup: "sub",
    commons: {"r1_1": "iron_ore", "r1_2": "flowfern", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_orange", "armor": "shell_orange"}, "tail_orange", "bag_orange", "wing_orange", "scale_orange"] },
  { id: "mizutsune", name: "Mizutsune", prefix: "Mizutsune",
    stars: 5, element: "water", color: "#42a5f5",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "flowfern", "r1_3": "monster_bone_s", "r2_1": "machalite_ore", "r2_2": "monster_bone_m", "r3_1": "dragonite_ore", "r3_2": "earth_crystal", "r3_3": "monster_bone_l", "r3_4": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_silver", "armor": "hide_purple"}, "tail_purple", "claw_purple", "hide_purple", "claw_purple", "plate_purple"] },
  { id: "zinogre", name: "Zinogre", prefix: "Zinogre",
    stars: 5, element: "thunder", color: "#ffca28",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "thunderbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_green", "armor": "shell_green"}, "tail_green", "body_silver", "claw_green", "claw_green", "plate_green"] },
  { id: "fulgur_anjanath", name: "Fulgur Anjanath", prefix: "F.Anja",
    stars: 5, element: "thunder", color: "#ffca28",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "thunderbug", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_silver", "armor": "scale_silver"}, "tail_silver", "bone_silver", "scale_silver", "scale_silver", "plate_silver"] },
  { id: "astalos", name: "Astalos", prefix: "Astalos",
    stars: 5, element: "thunder", color: "#ffca28",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "thunderbug", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "scale_green", "armor": "shell_green"}, "tail_green", "head_green", "wing_green", "claw_green", "plate_green"] },
  { id: "legiana", name: "Legiana", prefix: "Legiana",
    stars: 5, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "snow_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_blue", "armor": "hide_blue"}, "claw_blue", "wing_blue", "scale_blue", "plate_blue"] },
  { id: "ebony_odogaron", name: "Ebony Odogaron", prefix: "E.Odogaron",
    stars: 5, element: "dragon", color: "#ab47bc",
    isEvent: false, recipeGroup: "sub",
    commons: {"r1_1": "iron_ore", "r1_2": "dragonfell_berry", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_grey", "armor": "body_grey"}, "tail_grey", "claw_grey", "scale_grey", "plate_grey"] },
  { id: "deviljho", name: "Deviljho", prefix: "Deviljho",
    stars: 5, element: "dragon", color: "#ab47bc",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "dragonfell_berry", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_forest", "armor": "hide_forest"}, "tail_forest", "claw_forest", "hide_forest", "head_forest", "blood_forest"] },
  { id: "stygian_zinogre", name: "Stygian Zinogre", prefix: "S.Zinogre",
    stars: 5, element: "dragon", color: "#ab47bc",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "dragonfell_berry", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "carpenterbug"},
    exclusive: [{"weapon": "claw_grey", "armor": "shell_grey"}, "tail_grey", "body_grey", "claw_grey", "claw_grey", "plate_grey"] },
  { id: "pink_rathian", name: "Pink Rathian", prefix: "P.Rathian",
    stars: 5, element: "poison", color: "#ce93d8",
    isEvent: false, recipeGroup: "sub",
    commons: {"r1_1": "monster_bone_s", "r1_2": "toadstool", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_pink", "armor": "shell_pink"}, "wing_pink", "body_pink", "scale_pink", "plate_pink"] },
  { id: "vipertobikadachi", name: "Viper Tobi-Kadachi", prefix: "V.Tobi",
    stars: 5, element: "poison", color: "#ce93d8",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "parashroom", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "claw_orange", "armor": "scale_orange"}, "hide_orange", "wing_orange", "scale_orange", "body_orange", "body_orange"] },
  { id: "nightshade_paolumu", name: "Nightshade Paolumu", prefix: "N.Paolumu",
    stars: 5, element: "poison", color: "#ce93d8",
    isEvent: false, recipeGroup: "",
    commons: {"r1_1": "iron_ore", "r1_2": "sleep_herb", "r1_3": "monster_bone_s", "r1_4": "godbug", "r2_1": "machalite_ore", "r2_2": "monster_bone_m", "r3_1": "dragonite_ore", "r3_2": "earth_crystal", "r3_3": "monster_bone_plus", "r3_4": "monster_bone_l"},
    exclusive: [{"weapon": "scale_purple", "armor": "hide_purple"}, "wing_purple", "wing_purple", "scale_purple", "hide_purple"] },
  { id: "bazelgeuse", name: "Bazelgeuse", prefix: "Bazel.",
    stars: 5, element: "fire", color: "#ef5350",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "nitroshroom", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_silver", "armor": "shell_silver"}, "tail_silver", "claw_silver", "wing_silver", "body_red", "plate_silver"] },
  { id: "silver_rathalos", name: "Silver Rathalos", prefix: "S.Rathalos",
    stars: 6, element: "fire", color: "#ef5350",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "iron_ore", "r1_2": "fire_herb", "r2_1": "machalite_ore", "r3_1": "dragonite_ore", "r3_2": "earth_crystal"},
    exclusive: [{"weapon": "scale_grey", "armor": "claw_grey"}, "tail_grey", "body_grey", "scale_grey", "claw_grey", "plate_grey"] },
  { id: "teostra", name: "Teostra", prefix: "Teostra",
    stars: 6, element: "fire", color: "#ef5350",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "scale_red", "armor": "shell_red"}, "blood_red", "tail_red", "claw_red"] },
  { id: "namielle", name: "Namielle", prefix: "Namielle",
    stars: 6, element: "water", color: "#42a5f5",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "claw_purple", "armor": "hide_purple"}, "blood_red", "tail_purple", "body_purple"] },
  { id: "kirin", name: "Kirin", prefix: "Kirin",
    stars: 6, element: "thunder", color: "#ffca28",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "claw_blue", "armor": "hide_silver"}, "blood_red", "body_silver", "gem_blue"] },
  { id: "kushala_daora", name: "Kushala Daora", prefix: "Kushala",
    stars: 6, element: "ice", color: "#80deea",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "scale_grey", "armor": "shell_grey"}, "blood_red", "tail_grey", "claw_grey"] },
  { id: "nergigante", name: "Nergigante", prefix: "Nergi.",
    stars: 6, element: "dragon", color: "#ab47bc",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "scale_grey", "armor": "shell_grey"}, "blood_red", "tail_grey", "claw_grey"] },
  { id: "malzeno", name: "Malzeno", prefix: "Malzeno",
    stars: 6, element: "dragon", color: "#ab47bc",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "scale_silver", "armor": "shell_silver"}, "blood_red", "tail_silver", "claw_silver"] },
  { id: "gold_rathian", name: "Gold Rathian", prefix: "G.Rathian",
    stars: 6, element: "fire", color: "#ef5350",
    isEvent: true, recipeGroup: "rare",
    commons: {"r1_1": "monster_bone_s", "r1_2": "toadstool", "r2_1": "monster_bone_m", "r3_1": "monster_bone_l", "r3_2": "monster_bone_plus"},
    exclusive: [{"weapon": "scale_yellow", "armor": "shell_yellow"}, "wing_yellow", "body_yellow", "scale_yellow", "wing_yellow", "plate_yellow"] },
  { id: "chameleos", name: "Chameleos", prefix: "Chameleos",
    stars: 6, element: "dragon", color: "#ab47bc",
    isEvent: false, recipeGroup: "elder",
    commons: {"r4": "elder_dragon_blood"},
    exclusive: ["none", "none", {"weapon": "bone_purole", "armor": "hide_purple"}, "blood_red", "tail_purple", "claw_purple"] }
];

// ─── Derived datasets (built once at load) ────────────────────────────────────

function buildWeapons() {
  const out = [];
  for (const m of MONSTERS) {
    const types = WEAPONS_BY_TIER[m.stars] || WEAPONS_BY_TIER[6];
    for (const typeId of types) {
      out.push({
        id: `${m.id}__${typeId}`,
        monsterId: m.id,
        type: typeId,
        name: `${m.prefix} ${WEAPON_DESCRIPTORS[typeId]}`,
      });
    }
  }
  return out;
}

function buildArmor() {
  const out = [];
  for (const m of MONSTERS) {
    for (const slot of ARMOR_SLOTS) {
      out.push({
        id: `${m.id}__${slot}`,
        monsterId: m.id,
        slot,
        name: `${m.prefix} ${ARMOR_SLOT_NAMES[slot]}`,
      });
    }
  }
  return out;
}

const WEAPONS = buildWeapons();
const ARMOR   = buildArmor();

const MONSTER_BY_ID = Object.fromEntries(MONSTERS.map(m => [m.id, m]));
const WEAPON_BY_ID  = Object.fromEntries(WEAPONS.map(w => [w.id, w]));
const ARMOR_BY_ID   = Object.fromEntries(ARMOR.map(a => [a.id, a]));
