const MONSTER_WEAPONS = {
  'aknosom': ['gs', 'ls', 'db', 'lnc', 'gl', 'sa', 'ig'],
  'almudron': ['ls', 'hmr', 'db', 'gl', 'sa', 'lbg', 'bow'],
  'anjanath': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'gl', 'sa', 'ig', 'lbg', 'bow', 'hbg'],
  'arzuros': ['ls', 'hmr', 'hh', 'db', 'sa', 'bow', 'hbg'],
  'astalos': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'azure_rathalos': ['sns', 'gs', 'ls', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow'],
  'banbaro': ['gs', 'ls', 'hmr', 'db', 'gl', 'sa', 'lbg', 'bow'],
  'barioth': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'barroth': ['sns', 'gs', 'hmr', 'hh', 'lnc', 'gl', 'sa', 'lbg'],
  'basarios': ['ls', 'hmr', 'hh', 'lnc', 'cb', 'lbg', 'hbg'],
  'bazelgeuse': ['ls', 'hh', 'db', 'lnc', 'gl', 'sa', 'lbg'],
  'beotodus': ['gs', 'db', 'cb', 'ig', 'lbg'],
  'bishaten': ['sns', 'hmr', 'sa', 'lbg', 'bow', 'hbg'],
  'black_diablos': ['hmr', 'db', 'sa', 'cb', 'ig', 'bow', 'hbg'],
  'brute_tigrex': ['sns', 'gs', 'ls', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'chameleos': ['gs', 'ls', 'hmr', 'hh', 'db', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'chatacabra': ['sns', 'hmr', 'cb', 'ig', 'hbg'],
  'coral_pukei_pukei': ['sns', 'gs', 'hmr', 'hh', 'lnc', 'sa', 'ig', 'lbg', 'bow', 'hbg'],
  'deviljho': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'diablos': ['sns', 'gs', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'bow', 'hbg'],
  'ebony_odogaron': ['db', 'lnc', 'cb', 'ig', 'lbg'],
  'espinas': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'fulgur_anjanath': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'gl', 'sa', 'ig', 'lbg', 'bow', 'hbg'],
  'garangolm': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'glavenus': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'gold_rathian': ['sns', 'ls', 'hh', 'gl', 'sa', 'cb', 'lbg', 'bow', 'hbg'],
  'gossharag': ['sns', 'gs', 'hmr', 'lnc', 'cb', 'ig', 'lbg'],
  'great_girros': ['sns', 'gs', 'hmr', 'gl', 'cb'],
  'great_jagras': ['sns', 'gs', 'gl', 'sa', 'cb', 'lbg', 'hbg'],
  'great_wroggi': ['sns', 'ls', 'hmr', 'db', 'bow'],
  'jyuratodus': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'khezu': ['sns', 'gs', 'hmr', 'hh', 'db', 'gl', 'sa', 'ig', 'lbg', 'bow'],
  'kirin': ['sns', 'gs', 'hh', 'db', 'lnc', 'sa', 'ig', 'lbg', 'hbg'],
  'kulu_ya_ku': ['ls', 'hmr', 'hh', 'db', 'lnc', 'ig', 'bow'],
  'kushala_daora': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'lagombi': ['gs', 'ls', 'db', 'gl', 'sa', 'ig', 'hbg'],
  'legiana': ['sns', 'gs', 'ls', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'lunagaron': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'magnamalo': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'malzeno': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'mizutsune': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'namielle': ['sns', 'ls', 'hh', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'nargacuga': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'nergigante': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'nightshade_paolumu': ['sns', 'gs', 'hmr', 'hh', 'lnc', 'sa', 'ig', 'lbg', 'bow', 'hbg'],
  'odogaron': ['db', 'lnc', 'cb', 'ig', 'lbg'],
  'paolumu': ['sns', 'hh', 'sa', 'lbg'],
  'pink_rathian': ['sns', 'ls', 'hh', 'gl', 'cb', 'bow'],
  'pukei_pukei': ['sns', 'gs', 'hmr', 'hh', 'lnc', 'sa', 'ig', 'bow', 'hbg'],
  'quematrice': ['sns', 'gs', 'ls', 'db', 'lnc', 'gl', 'bow'],
  'radobaan': ['sns', 'gs', 'hmr', 'hh', 'hbg'],
  'rajang': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'rathalos': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow'],
  'rathian': ['sns', 'ls', 'hh', 'gl', 'sa', 'cb', 'ig', 'bow', 'hbg'],
  'seregios': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'shogun_ceanataur': ['gs', 'ls', 'hmr', 'db', 'lnc', 'cb', 'bow', 'hbg'],
  'silver_rathalos': ['sns', 'gs', 'ls', 'hmr', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow'],
  'somnacanth': ['gs', 'ls', 'hmr', 'hh', 'db', 'cb', 'ig'],
  'stygian_zinogre': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'teostra': ['sns', 'gs', 'ls', 'hmr', 'hh', 'lnc', 'sa', 'cb', 'lbg', 'bow', 'hbg'],
  'tigrex': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'tobi_kadachi': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
  'tzitzi_ya_ku': ['ls', 'db', 'ig', 'hbg'],
  'vipertobikadachi': ['ls', 'db', 'gl', 'cb', 'ig', 'bow', 'hbg'],
  'volvidon': ['hmr', 'lnc', 'gl', 'sa', 'cb', 'hbg'],
  'zinogre': ['sns', 'gs', 'ls', 'hmr', 'hh', 'db', 'lnc', 'gl', 'sa', 'cb', 'ig', 'lbg', 'bow', 'hbg'],
};
