const SKILL_NAMES = {
  'abnormal_status_enhancement': 'Status Sneak Attack',
  'airborne': 'Skyward Striker',
  'armor_up': 'Litheness',
  'artful_dodger': 'Artful Dodger',
  'artillery': 'Artillery',
  'attack_boost': 'Attack Boost',
  'attack_boost_secret': 'Advanced Attack Boost',
  'attack_up_critical_down': 'Raw Power',
  'auto_just_dodge': 'Perfectionist',
  'ballistic': 'Ballistics',
  'blast_attack': 'Blast Attack',
  'blast_resistance': 'Blast Resistance',
  'bleeding_resistance': 'Bleeding Resistance',
  'bloodblight_cloak': 'Blood Cloak',
  'bravery': 'Valor',
  'break_attack_boost': 'Pursuit',
  'brutal_strike': 'Critical Ferocity',
  'bubbly_dance': 'Bubbly Dance',
  'buildup_boost': 'Buildup Boost',
  'burst': 'Burst',
  'burst_dodger': 'Offensive Dodger',
  'burst_secret': 'Advanced Burst',
  'chameleos_poison': 'Chameleos Venomist',
  'charge_up': 'Blunt Force',
  'concentration': 'Concentration',
  'critical_boost': 'Critical Boost',
  'critical_element': 'Critical Element',
  'critical_eye': 'Critical Eye',
  'deathgaron': 'Bleeding Edge',
  'defense_boost': 'Defense Boost',
  'disable_perfect_evade': 'Reckless',
  'divine_blessing': 'Divine Blessing',
  'dragon_attack': 'Dragon Attack',
  'dragon_attack_boost_secret': 'Advanced Dragon Attack',
  'earplugs': 'Earplugs',
  'ending_shot': 'Final Shot',
  'enhancement_normal_ammo': 'Normal/Element Ammo Boost',
  'enhancement_slicing_ammo': 'Slicing Ammo Boost',
  'evade_extender': 'Evade Extender',
  'evasive_reload': 'Evading Reload',
  'feat_of_agility': 'Quick Work',
  'fighting_spirit': 'Fighting Spirit',
  'fire_attack': 'Fire Attack',
  'fire_resistance': 'Fire Resistance',
  'firm_foothold': 'Firm Foothold',
  'focus': 'Focus',
  'fortify': 'Fortify',
  'guard': 'Guard',
  'guard_up': 'Guard Up',
  'guarding_reload': 'Defensive Loading',
  'guts': 'Guts',
  'health_boost': 'Health Boost',
  'hellfire_cloak': 'Hellfire Cloak',
  'heroics': 'Heroics',
  'high_performance_dragon': 'Vital Dragon',
  'high_performance_fire': 'Vital Fire',
  'high_performance_ice': 'Vital Ice',
  'high_performance_thunder': 'Vital Thunder',
  'high_performance_water': 'Vital Water',
  'ice_attack': 'Ice Attack',
  'ice_attack_boost_secret': 'Advanced Ice Attack',
  'ice_resistance': 'Ice Resistance',
  'kirin_robe': 'Kirin Flashstorm',
  'kushala_bless': 'Kushala Frostwind',
  'last_stand': 'Last Stand',
  'latent_power': 'Latent Power',
  'lock_on': 'Lock On',
  'malzeno_blood': 'Malzeno Crimsonblood',
  'morph_attack_boost': 'Morph Attack Boost',
  'morph_boost': 'Morph Boost',
  'move_forward_strengthen': 'Dauntless',
  'multi_attack_boost': 'Shared Sword',
  'multiplayer_boost': 'Shared Shield',
  'namielle_wave': 'Namielle Electrowave',
  'nergigante_greed': 'Nergigante Avidity',
  'offensive_guard': 'Offensive Guard',
  'paralysis_attack': 'Paralysis Attack',
  'paralysis_resistance': 'Paralysis Resistance',
  'part_break_special_boost': 'Special Partbreaker',
  'part_breaker_tail': 'Tail Partbreaker',
  'partbreaker': 'Partbreaker',
  'peak_performance': 'Peak Performance',
  'perfect_evade_attack_boost': 'Aggressive Dodger',
  'perfect_evade_sp_charge': 'Evasive Concentration',
  'poison_attack': 'Poison Attack',
  'poison_resistance': 'Poison Resistance',
  'power_burst': 'Combo Master',
  'power_prolonger': 'Power Prolonger',
  'powerhouse': 'Attack Efficacy',
  'powerhouse_critical': 'Critical Strength',
  'pursuit_paralysis': 'Paralysis Exploit',
  'pursuit_poison': 'Poison Exploit',
  'recoil_down': 'Recoil Down',
  'reload_speed': 'Reload Speed',
  'resentment': 'Resentment',
  'resuscitate': 'Resuscitate',
  'rising_tide': 'Rising Tide',
  'sleep_attack': 'Sleep Attack',
  'sleep_enhancement': 'Rude Awakener',
  'sleep_resistance': 'Sleep Resistance',
  'slugger': 'Slugger',
  'sneak_attack': 'Sneak Attack',
  'sp_insurance': 'Special Insurance',
  'sp_overdrive': 'Elemental Release',
  'spare_shot': 'Spare Shot',
  'special_boost': 'Special Boost',
  'teostra_bless': 'Teostra Blastpowder',
  'thunder_attack': 'Thunder Attack',
  'thunder_attack_boost_secret': 'Advanced Thunder Attack',
  'thunder_resistance': 'Thunder Resistance',
  'tremor_resistance': 'Tremor Resistance',
  'water_attack': 'Water Attack',
  'water_attack_boost_secret': 'Advanced Water Attack',
  'water_resistance': 'Water Resistance',
  'weakness_exploit': 'Weakness Exploit',
  'windproof': 'Windproof'
};
